"""The dashboard's network layer — card art, webfonts, and the dev server.

This module exists to keep a promise the rest of the codebase makes: **command
modules never touch the network; loaders do.** `cmd_dashboard` computes and
writes data files and cannot open a socket — it does not import urllib or http
at all, at any nesting level, which the C1 constraint tests assert against the
AST rather than against behaviour. Every byte the dashboard fetches is fetched
here, exactly as `load_cards` / `load_rules` own the fetching for `mtg rebuild`.

Nothing in here is imported unless you actually run `mtg dashboard --build` or
`--serve`: `cmd_dashboard` imports this module lazily, the same trick
`cmd_admin._loader` uses, so a plain `mtg card` never pulls the network stack
into sys.modules.

Paths are passed in rather than imported from `cmd_dashboard`. That keeps the
dependency one-way (command -> loader) with no import cycle, and makes every
function here testable against a temp directory.

stdlib only (C6).
"""
from __future__ import annotations

import re
import time
from pathlib import Path

import db

# ------------------------------------------------------------------- images
#: Scryfall's own guidance: identify yourself, and stay well under ~10 req/s.
IMAGE_SLEEP = 0.10
IMAGE_TIMEOUT = 30

# -------------------------------------------------------------------- fonts
#: The Google Fonts CSS API decides which font FORMAT to serve from the User-
#: Agent. Asked as `mtg-brain/1.0` it replies with .ttf; asked as a current
#: browser it replies with .woff2, which is roughly half the bytes and what
#: every browser that will ever open this page actually wants. This one request
#: therefore claims to be Chrome. It is the only place in the project that
#: misrepresents itself, and it does so to pick a file format — nothing else.
BROWSER_UA = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
)
GOOGLE_FONTS_CSS = (
    "https://fonts.googleapis.com/css2"
    "?family=JetBrains+Mono:wght@400;500"
    "&family=Orbitron:wght@700;900"
    "&display=swap"
)
FONT_TIMEOUT = 30

FONTS_CSS_HEADER = (
    "/* Generated by `mtg dashboard --build`. Do not edit — it is overwritten.\n"
    "   Every src below points at a LOCAL file in this folder, so the page keeps\n"
    "   its type with the network off (constraint C5). font-display:swap means a\n"
    "   missing file degrades to the system stack in tokens.css instead of\n"
    "   blocking paint. */\n"
)
FONTS_CSS_NOOP = (
    "/* `mtg dashboard --build` could not reach the Google Fonts API, so no\n"
    "   webfonts are cached and this file is deliberately empty.\n"
    "\n"
    "   This is not a failure state for the page. --font-display / --font-body /\n"
    "   --font-mono in tokens.css each end in a system fallback stack, so Remy's\n"
    "   Lair still renders as designed — with system faces instead of Orbitron\n"
    "   and JetBrains Mono. Re-run `mtg dashboard --build` when online to cache\n"
    "   them. */\n"
)


def _http_get(url: str, user_agent: str, timeout: int) -> bytes:
    """GET, identifying ourselves. urllib is imported inside the function so
    that importing this module still costs nothing until a fetch happens."""
    import urllib.request

    request = urllib.request.Request(
        url, headers={"User-Agent": user_agent, "Accept": "*/*"}
    )
    with urllib.request.urlopen(request, timeout=timeout) as resp:
        return resp.read()


# ============================================================= card art cache
def cache_images(conn, oracle_ids, img_dir: Path, force: bool = False) -> dict:
    """Download card art to <img_dir>/<oracle_id>.jpg.

    One card failing must never abort the build: 230 good images plus a warning
    beats no dashboard at all. Each file is written through a .part sibling and
    renamed, so an interrupted download can never be mistaken for a cached one
    on the next run.
    """
    wanted = sorted(set(oracle_ids))
    result = {
        "wanted": len(wanted), "downloaded": 0, "cached": 0,
        "no_url": 0, "failed": 0, "bytes": 0, "errors": [],
    }
    if not wanted:
        return result

    img_dir.mkdir(parents=True, exist_ok=True)
    marks = ",".join("?" * len(wanted))
    urls = {
        row["oracle_id"]: row["image_normal"]
        for row in conn.execute(
            f"SELECT oracle_id, image_normal FROM cards WHERE oracle_id IN ({marks})",
            wanted,
        )
    }

    for index, oracle_id in enumerate(wanted):
        dest = img_dir / f"{oracle_id}.jpg"
        if dest.exists() and dest.stat().st_size > 0 and not force:
            result["cached"] += 1
            result["bytes"] += dest.stat().st_size
            continue
        url = (urls.get(oracle_id) or "").strip()
        if not url:
            result["no_url"] += 1
            continue
        try:
            blob = _http_get(url, db.USER_AGENT, IMAGE_TIMEOUT)
            tmp = dest.with_suffix(".part")
            tmp.write_bytes(blob)
            tmp.replace(dest)
            result["downloaded"] += 1
            result["bytes"] += len(blob)
        except Exception as exc:  # noqa: BLE001 — any failure is per-card news
            result["failed"] += 1
            result["errors"].append(f"{oracle_id}: {type(exc).__name__}: {exc}")
        if index + 1 < len(wanted):
            time.sleep(IMAGE_SLEEP)
    return result


# =============================================================== webfont cache
FONT_FACE_RE = re.compile(
    r"(?:/\*\s*(?P<subset>[^*]+?)\s*\*/\s*)?@font-face\s*\{(?P<body>[^}]*)\}", re.S
)


def _css_prop(body: str, name: str):
    match = re.search(rf"{name}\s*:\s*([^;]+);", body, re.I)
    return match.group(1).strip() if match else None


def _slug(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", (text or "").lower()).strip("-") or "x"


def parse_font_faces(css: str) -> list:
    """Google Fonts CSS -> [{family, weight, style, subset, url, unicode_range}].

    The subset name ('latin', 'cyrillic-ext', ...) comes from the `/* ... */`
    comment Google emits above each block; it is what makes the cached filenames
    stable and readable instead of hash soup.
    """
    faces = []
    for match in FONT_FACE_RE.finditer(css):
        body = match.group("body")
        src = _css_prop(body, "src") or ""
        url = re.search(r"url\((['\"]?)(.*?)\1\)", src)
        family = (_css_prop(body, "font-family") or "").strip("'\" ")
        if not url or not family:
            continue
        faces.append(
            {
                "family": family,
                "weight": _css_prop(body, "font-weight") or "400",
                "style": _css_prop(body, "font-style") or "normal",
                "subset": _slug(match.group("subset") or ""),
                "url": url.group(2),
                "unicode_range": _css_prop(body, "unicode-range"),
            }
        )
    return faces


def cache_fonts(font_dir: Path, css_path: Path, force: bool = False) -> dict:
    """Cache Orbitron + JetBrains Mono locally and write fonts.css beside them.

    A font failure NEVER fails the build. tokens.css ends every family in a
    system fallback stack precisely so this step is optional; if anything here
    goes wrong we say so loudly and write a no-op fonts.css rather than leaving
    a stale or half-written one behind.
    """
    result = {
        "ok": False, "faces": 0, "downloaded": 0, "cached": 0,
        "failed": 0, "bytes": 0, "families": [], "errors": [], "css_bytes": 0,
    }
    font_dir.mkdir(parents=True, exist_ok=True)
    try:
        css = _http_get(GOOGLE_FONTS_CSS, BROWSER_UA, FONT_TIMEOUT).decode("utf-8")
        faces = parse_font_faces(css)
        if not faces:
            raise ValueError("no @font-face blocks found in the API response")
    except Exception as exc:  # noqa: BLE001
        result["errors"].append(f"{type(exc).__name__}: {exc}")
        css_path.write_text(FONTS_CSS_NOOP, encoding="utf-8")
        result["css_bytes"] = css_path.stat().st_size
        return result

    blocks, seen = [FONTS_CSS_HEADER], set()
    for face in faces:
        filename = f"{_slug(face['family'])}-{face['weight']}-{face['subset']}.woff2"
        if filename in seen:
            continue
        seen.add(filename)
        dest = font_dir / filename
        try:
            if dest.exists() and dest.stat().st_size > 0 and not force:
                result["cached"] += 1
            else:
                dest.write_bytes(_http_get(face["url"], BROWSER_UA, FONT_TIMEOUT))
                result["downloaded"] += 1
            result["bytes"] += dest.stat().st_size
        except Exception as exc:  # noqa: BLE001
            result["failed"] += 1
            result["errors"].append(f"{filename}: {type(exc).__name__}: {exc}")
            continue

        rule = [
            "@font-face {",
            f"  font-family: '{face['family']}';",
            f"  font-style: {face['style']};",
            f"  font-weight: {face['weight']};",
            "  font-display: swap;",
            f"  src: url('{filename}') format('woff2');",
        ]
        if face["unicode_range"]:
            rule.append(f"  unicode-range: {face['unicode_range']};")
        rule.append("}")
        blocks.append("\n".join(rule))

    css_path.write_text("\n".join(blocks) + "\n", encoding="utf-8")
    result["css_bytes"] = css_path.stat().st_size
    result["faces"] = len(seen)
    result["families"] = sorted({f["family"] for f in faces})
    result["ok"] = result["faces"] > 0 and result["failed"] == 0
    return result


# ================================================================= dev server
def make_server(root: Path, port: int):
    """A static file server for `mtg dashboard --serve`, bound to loopback.

    Returns the server; the caller prints the banner and runs it, so all the
    user-facing text stays in the command module.

    127.0.0.1 rather than 0.0.0.0 on purpose: this is a convenience for getting
    a real http:// origin while developing, not a thing to put on a LAN. The
    page itself needs no server at all — it opens from file://.
    """
    from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer

    class Handler(SimpleHTTPRequestHandler):
        # `directory=` instead of chdir: the CLI must not mutate the process's
        # working directory out from under anything else.
        def __init__(self, *args, **kwargs):
            super().__init__(*args, directory=str(root), **kwargs)

    return ThreadingHTTPServer(("127.0.0.1", port), Handler)
